# Generated by Django 4.2.1 on 2023-05-13 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('Subscription', models.IntegerField(max_length=3)),
                ('type_of', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(max_length=3)),
                ('grade', models.CharField(max_length=20)),
                ('phone', models.IntegerField(max_length=11)),
                ('gender', models.CharField(max_length=6)),
            ],
        ),
    ]
